# Generated by Django 4.0.4 on 2022-05-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_name', models.CharField(max_length=100, verbose_name='name')),
                ('books_author', models.CharField(max_length=100, verbose_name='author')),
                ('books_year', models.CharField(max_length=100, verbose_name='year')),
                ('books_edition', models.CharField(max_length=100, verbose_name='edition')),
                ('books_exposition', models.TextField(verbose_name='exposition')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_books', models.CharField(max_length=100, verbose_name='form')),
                ('pub_date', models.DateTimeField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Librarier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=100, verbose_name='name')),
                ('librarier_login', models.CharField(max_length=100, verbose_name='login')),
                ('librarier_password', models.CharField(max_length=100, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='Regform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regform', models.CharField(max_length=100, verbose_name='registration of books')),
                ('regfrom', models.CharField(max_length=100, verbose_name='salary')),
                ('pub_date', models.DateTimeField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(max_length=100, verbose_name='login')),
                ('user_password', models.CharField(max_length=100, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=100, verbose_name='name')),
                ('comment_text', models.CharField(max_length=200, verbose_name='comment')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulib.books')),
            ],
        ),
    ]
